# Generated by Django 5.0.3 on 2024-04-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pagesuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesuser',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='pagesuser',
            name='users',
        ),
        migrations.AddField(
            model_name='pagesuser',
            name='pages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.pages'),
        ),
        migrations.AddField(
            model_name='pagesuser',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
