# Generated by Django 5.0.3 on 2024-04-18 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_pagesuser_pages_remove_pagesuser_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesuser',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='pagesuser',
            name='users',
        ),
        migrations.AddField(
            model_name='pagesuser',
            name='pages',
            field=models.ManyToManyField(to='myapp.pages'),
        ),
        migrations.AddField(
            model_name='pagesuser',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
