# Generated by Django 5.0.3 on 2024-04-18 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_pagesuser_pages_remove_pagesuser_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagesUser',
            new_name='Permissions',
        ),
    ]
