# Generated by Django 5.0.3 on 2024-04-18 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_pagesuser_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
    ]
